import '@/assets/styles/globals.css';

export const metadata = {
    title: 'Property Pulse',
    description: 'Generated by create next app',
};

const MainLayout = ({ children }) => {
    return ( 
    <html>
        <body>
           <main> {children} </main> 
        </body>
    </html> 
    );
};
 
export default MainLayout;
